# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ColorCategorizer
                                 A QGIS plugin
 Test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-04
        copyright            : (C) 2024 by Philippine Statistics Authority
        email                : test@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ColorCategorizer class from file ColorCategorizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .color_categorizer import ColorCategorizer
    return ColorCategorizer(iface)
